# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoDeli' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '14.4'

  # Pods for CoDeli
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'CoDeliTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoDeliUITests' do
    # Pods for testing
  end

end
